// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: employee_project.sql

package database

import (
	"context"
)

const assignEmployeeToProject = `-- name: AssignEmployeeToProject :one
INSERT INTO employee_project(
    employee_id,
    project_id
) VALUES(
    $1, $2
)
RETURNING employee_id, project_id
`

type AssignEmployeeToProjectParams struct {
	EmployeeID int64 `json:"employee_id"`
	ProjectID  int64 `json:"project_id"`
}

func (q *Queries) AssignEmployeeToProject(ctx context.Context, arg AssignEmployeeToProjectParams) (EmployeeProject, error) {
	row := q.db.QueryRowContext(ctx, assignEmployeeToProject, arg.EmployeeID, arg.ProjectID)
	var i EmployeeProject
	err := row.Scan(&i.EmployeeID, &i.ProjectID)
	return i, err
}
