// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: position.sql

package database

import (
	"context"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO position(
    name
)VALUES(
    $1
)
RETURNING id, name
`

func (q *Queries) CreatePosition(ctx context.Context, name string) (Position, error) {
	row := q.db.QueryRowContext(ctx, createPosition, name)
	var i Position
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
