// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: project.sql

package database

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO project(
    name
)VALUES(
    $1
)
RETURNING id, name
`

func (q *Queries) CreateProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
