// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: state.sql

package database

import (
	"context"
)

const createState = `-- name: CreateState :one
INSERT INTO state(
    name
)VALUES(
    $1
)
RETURNING id, name
`

func (q *Queries) CreateState(ctx context.Context, name string) (State, error) {
	row := q.db.QueryRowContext(ctx, createState, name)
	var i State
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
